### PR TITLE
Proposed fix for the following known issues.

### PR DESCRIPTION
**Pull request by manwar**
Hi Julien,

As you joked at the end of the lightning talk, I proposed the PR to address the known issues.
  1. Remove duplicate slashes in output.
  2. Show .cgi in the file list.

Also added escaping special characters when doing search/replace.
Please review the PR.

Many Thanks.
Best Regards,
Mohammad S Anwar

### CODE REVIEW

**Comment by simbabque** [comment]
Thanks a lot! :)

**Comment by manwar** [comment]
I am glad I was able to clear the two issues. :-)

**Comment by simbabque** [comment]
I found a bug in your fix, but I've got it sorted out now. You put the quotes in the wrong place. ;)

I will be adding tests and then release.

**Comment by manwar** [comment]
My bad...sorry :-(

**Pull request merged**
